interface AnalyzePRProps {
  files: any[];
}

export const analyzePR = ({ files }: AnalyzePRProps): string => {
  // Basic analysis - this is where you'd implement your custom logic
  const fileCount = files.length;
  const additions = files.reduce((sum, file) => sum + (file.additions || 0), 0);
  const deletions = files.reduce((sum, file) => sum + (file.deletions || 0), 0);

  return `## PR Analysis

**Files Changed:** ${fileCount}
**Additions:** +${additions}
**Deletions:** -${deletions}

---
*This analysis was generated by the Saltman GitHub Action*`;
};
